mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.mldnboot.vo             # 定义所有操作类的别名所在包

spring: 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/mldn           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mysqladmin                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 1                                   # 数据库连接池的最小维持连接数    
      initial-size: 1                               # 初始化提供的连接数
      max-total: 1                                  # 最大的连接数
      max-wait-millis: 3000                         # 等待连接获取的最大超时时间
server:
  port: 80
