spring: 
  redis:                    # Redis相关配置
    host: redis-server    # 主机名称
    port: 6379              # 端口号
    password: mldnjava      # 认证密码
    timeout: 1000         # 连接超时时间
    database: 0         # 默认数据库
    pool:           # 连接池配置
      max-active: 10    # 最大连接数
      max-idle: 8       # 最大维持连接数
      min-idle: 2     # 最小维持连接数
      max-wait: 100 # 最大等待连接超时时间
server:
  port: 80
