#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

server:
  servlet:
    context-path: /springboot

logging:
  level:
#    root: debug
    com.imooc.springboot.transaction.mapper: debug
    org.springframework.jdbc.datasource: debug
